default: &default
  adapter: postgresql
  encoding: unicode
  username: headless_bdd
  password: headless-bdd0192
  pool: 5

development:
  <<: *default
  database: headless-bdd_development
  host: localhost

test:
  <<: *default
  database: headless-bdd_test
  host: localhost

production:
  <<: *default
  database: headless-bdd_production
  username: headless_bdd
  password: <%= ENV['HEADLESS-BDD_DATABASE_PASSWORD'] %>
